// Generated by https://quicktype.io

export interface Products {
	data:  Product[];
	links?: Links;
	meta?:  Meta;
}

export interface Image{
	id?: string
	product_id?: string
	image: string
	description: string
	status: number
  }

export interface Product {
	id:               any;
	cod:              string;
	description:      string;
	quantity:         number;
	unit_price?:         number;
	category:         Category;
	provider:         Provider;
	brand?:            Brand;
	prices:           Price[];
	composeds?:		   Composed[];
	information?:      string;
	tags?:             string;
	minimum_stock:    number;
	expires:          boolean;
	product_type:     number;
	prescription:     boolean;
	ecommerce:        boolean;
	default_discount: number;
	default_commission: number;
	measure?: 		   string;
	extra?: 		   string | any;
	images?: 		   Image[];

}

export interface Brand {
	id:       number;
	name:     string;
	provider?: Provider;
}

export interface Provider {
	id:           number;
	name:         string;
	email?:        string;
	phone?:        string;
	document?:     string;
	contact_type?: number;
}

export interface Category {
	id:            number | string;
	name:          string;
	pronoun:       string;
	img?:           string | null;
	category_type?: number | string;
	subcategories: SubCategories[];
	dependable?:    null | string;
}


export interface SubCategories {
	id:            number | string;
	name:          string;
	pronoun:       string;
	img?:           null;
	category_type?: number | string;
	dependable?:    null | string;
}

export interface Price {
	id:         number;
	qty:        number;
	price:      number;
	price_type: number;
}

export interface Composed {
	product:        number;
	qty:        	number;
	added_product:	number;
}

export interface Links {
	first?: string;
	last?:  string;
	prev?:  null;
	next?:  string;
}

export interface Meta {
	current_page?: number;
	from?:         number;
	last_page?:    number;
	links?:        Link[];
	path?:         string;
	per_page?:     number;
	to?:           number;
	total?:        number;
}

export interface Link {
	url?:    null | string;
	label?:  string;
	active?: boolean;
}
