// Generated by https://quicktype.io

export interface Products {
	data:  Product[];
	links?: Links;
	meta?:  Meta;
}

export interface Product {
	id:               any;
	cod:              string;
	description:      string;
	quantity:         number;
	category:         Category;
	provider:         Provider;
	brand?:            Brand;
	prices?:           Price[];
	information?:      string;
	tags?:             string;
	minimum_stock:    number;
	expires?:          number;
	product_type:     number;
	prescription?:     number;
	promotion?:        number;
	ecommerce?:        number;
	default_discount?: number;
}

export interface Brand {
	id:       number;
	name:     string;
	provider?: Provider;
}

export interface Provider {
	id:           number;
	name:         string;
	email?:        string;
	phone?:        string;
	document?:     string;
	contact_type?: number;
}

export interface Category {
	id:            number | string;
	name:          string;
	pronoun:       string;
	img?:           null;
	category_type?: number | string;
	dependable?:    null;
}

export interface Price {
	id:         number;
	qty:        number;
	price:      number;
	price_type: number;
}

export interface Links {
	first?: string;
	last?:  string;
	prev?:  null;
	next?:  string;
}

export interface Meta {
	current_page?: number;
	from?:         number;
	last_page?:    number;
	links?:        Link[];
	path?:         string;
	per_page?:     number;
	to?:           number;
	total?:        number;
}

export interface Link {
	url?:    null | string;
	label?:  string;
	active?: boolean;
}
