'use client'

import './globals.css'
import { ProSidebarProvider } from "react-pro-sidebar";
import {Header, SideBar} from "./components";
import { ConfigContextProvider } from "../contexts/config-context";


export const metadata = {
  title: 'Sistema de inventario',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ConfigContextProvider>
      <ProSidebarProvider>
      <html lang="en">
        <body>
            <div className="container mx-auto px-1">
            <Header />
            <div>
              <div>
              <SideBar />
              </div>
              <div className="w-full">
                {children}
              </div>
            </div>  
          </div>
        </body>
      </html>
    </ProSidebarProvider>
  </ConfigContextProvider>

  )
}
